ablation:

  model_name_str: null
  model_type: null

  ablations_types: null
  ablations_layers_lst: null
  ablate_n_heads_per_layer: null
  head_selection_strategy: random
    # "random": Randomly select heads to ablate
    # "srank" : Select heads based on stable rank of the kernel matrix

  # Device configuration
  device: cuda 

  # If head_selection_strategy is null, then default to ablate to heads@xpp
  to_heads_at_xpp:
    threshold_pct: 1.0
    chosen_layers: null
    num_heads_per_layer_to_skip: 0
    layers_to_keep_at_headsxpp: null
    chosen_layers_mlp: null
