defaults:
  - models
  - evaluation
  - plotting
  - _self_

attention_entropy:
  work_dir: ${oc.env:WORK}
  output_root: ${attention_entropy.work_dir}/attention_scores

  data_dir: ${attention_entropy.work_dir}/data/base40
  system_names: null
  num_subdirs: null
  num_samples_per_subdir: null

  context_length: 512
  prediction_length: 512
  window_style: sampled
  num_test_instances: 1
  window_stride: 1
  window_start_time: null
  random_seed: ${eval.rseed}

  max_series_per_system: null
  max_windows_per_series: null
  max_windows_total: null

  num_samples: 10
  deterministic: false
