chronos:

  deterministic: false

  limit_prediction_length: false

  model_id: amazon/chronos-t5-base
  model_type: seq2seq

  # model params
  random_init: false # NOTE: set to false for fine-tuning, very important!
  tie_embeddings: true

  context_length: 512
  num_samples: 20

  # vocab (tokens)
  n_tokens: 4096
  n_special_tokens: 2
  pad_token_id: 0
  eos_token_id: 1
  use_eos_token: true

  tokenizer_class: "MeanScaleUniformBins"
  tokenizer_kwargs:
    low_limit: -15.0
    high_limit: 15.0

  temperature: 1.0
  top_k: 50
  top_p: 1.0

chronos_bolt:

  limit_prediction_length: false

  model_id: amazon/chronos-bolt-base
  context_length: 512

chronos2:

  model_id: amazon/chronos-2
  context_length: 8192

timesfm:

  model_id: google/timesfm-2.5-200m-pytorch
  context_length: 2048

toto:

  model_id: Datadog/Toto-Open-Base-1.0
  context_length: 4096

  num_samples: null
  samples_per_batch: 20
  use_kv_cache: true
  pad_short_series: false

moirai:

  model_id: Salesforce/moirai-1.1-R-base
  context_length: 4000
  prediction_length: 1
  patch_size: 32
  num_samples: 100
  target_dim: 1